// <auto-generated />
using System;
using LancachePrefill.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LancachePrefill.Data.Migrations
{
    [DbContext(typeof(PrefillDbContext))]
    [Migration("20260228143516_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("LancachePrefill.Data.Entities.CacheFile", b =>
                {
                    b.Property<string>("FileHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("file_hash");

                    b.Property<long>("DepotId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("depot_id");

                    b.HasKey("FileHash");

                    b.HasIndex("DepotId");

                    b.ToTable("cache_files");
                });

            modelBuilder.Entity("LancachePrefill.Data.Entities.DepotAppMapping", b =>
                {
                    b.Property<long>("DepotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("depot_id");

                    b.Property<long>("AppId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("app_id");

                    b.Property<string>("AppName")
                        .HasColumnType("TEXT")
                        .HasColumnName("app_name");

                    b.HasKey("DepotId");

                    b.ToTable("depot_app_map");
                });

            modelBuilder.Entity("LancachePrefill.Data.Entities.DownloadedDepot", b =>
                {
                    b.Property<long>("DepotId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("depot_id");

                    b.Property<long>("ManifestId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("manifest_id");

                    b.Property<DateTime>("DownloadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("downloaded_at")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("DepotId", "ManifestId");

                    b.ToTable("downloaded_depots");
                });

            modelBuilder.Entity("LancachePrefill.Data.Entities.ScanResultEntity", b =>
                {
                    b.Property<long>("AppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("app_id");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("app_name");

                    b.Property<bool>("Cached")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cached");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT")
                        .HasColumnName("error");

                    b.Property<DateTime>("ScannedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("scanned_at")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("AppId");

                    b.ToTable("scan_results");
                });

            modelBuilder.Entity("LancachePrefill.Data.Entities.SelectedApp", b =>
                {
                    b.Property<long>("AppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("app_id");

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("added_at")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<bool>("Evicted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("evicted");

                    b.HasKey("AppId");

                    b.ToTable("selected_apps");
                });

            modelBuilder.Entity("LancachePrefill.Data.Entities.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("settings");
                });
#pragma warning restore 612, 618
        }
    }
}
