// Shared reactive state — single source of truth
export const state = {
  apps: [],
  scanMap: {},
  library: [],
  appNames: {},
  evictedCount: 0,
  utd: {},
  manifests: {},
  cachedManifests: {},
  appStatus: {},
  prefillDoneHandled: false,
  scanDoneHandled: false,
  scanWasRunning: false,
  prefillWasRunning: false,
  lastVersion: -1,
  libPage: 1,
  libPageSize: 100,
  lastSyncTime: null,
  lastScanTime: null,
  lancacheIp: null,
  sseRetryDelay: 1500,
  sseMaxRetry: 30000,
  cacheGames: [],
  cacheLoaded: false,
  evictedLoaded: false,
  syncQueue: [],
  isQueuedPrefill: false,
};